from .task import Task
from .panel import PatchPanel
from .verifier import VerifierConfig
from .result import VerificationResult
"""Domain models for VerifierCI.

__all__ = ["Task", "PatchPanel", "VerifierConfig", "VerificationResult"]
SDD Section 4 and Section 5.
"""

from __future__ import annotations

from .panel import (
    Adjudication,
    AgentRun,
    PatchCase,
    PatchPanel,
    PatchPanelMembership,
    Witness,
    panel_digest,
    validate_lineage,
    validate_membership,
)
from .protocol import (
    AcceptanceCell,
    AnalysisPlan,
    AuditOptions,
    AuditResult,
    BenchmarkVersion,
    BootstrapResult,
    CommandSpec,
    ExecutionCapture,
    GateEvidence,
    GatePolicy,
    ImportBundle,
    ImportRequest,
    Job,
    LocalImportManifest,
    MetricTerm,
    ParsedOutcome,
    ResourceUsage,
    ReviewAgreement,
    ReviewVote,
    SandboxPolicy,
    TaskPin,
    TelemetryEvent,
    TestReport,
    TestResult,
    TrainingExample,
    WorkerRequest,
    WorkerResponse,
    decode_record,
    encode_record,
    validate_wire_version,
)
from .result import (
    AcceptanceMatrix,
    Artifact,
    AuditManifest,
    AuditRun,
    EvaluationAttempt,
    GateDecision,
    MetricResult,
    result_digest,
    validate_attempt,
    validate_matrix,
)
from .task import (
    Contract,
    Environment,
    RepositorySnapshot,
    Requirement,
    Task,
    canonical_bytes,
    canonical_repr,
    compare_versions,
    contract_hash,
    requirement_hash,
    validate_task,
)
from .verifier import (
    VerifierManifest,
    VerifierVersion,
    manifest_hash,
    register_verifier,
    resolve_command,
    validate_verifier,
)

__all__ = [
    "AcceptanceCell",
    "AcceptanceMatrix",
    "Adjudication",
    "AgentRun",
    "AnalysisPlan",
    "Artifact",
    "AuditManifest",
    "AuditOptions",
    "AuditResult",
    "AuditRun",
    "BenchmarkVersion",
    "BootstrapResult",
    "CommandSpec",
    "Contract",
    "Environment",
    "EvaluationAttempt",
    "ExecutionCapture",
    "GateDecision",
    "GateEvidence",
    "GatePolicy",
    "ImportBundle",
    "ImportRequest",
    "Job",
    "LocalImportManifest",
    "MetricResult",
    "MetricTerm",
    "ParsedOutcome",
    "PatchCase",
    "PatchPanel",
    "PatchPanelMembership",
    "RepositorySnapshot",
    "Requirement",
    "ResourceUsage",
    "ReviewAgreement",
    "ReviewVote",
    "SandboxPolicy",
    "Task",
    "TaskPin",
    "TelemetryEvent",
    "TestReport",
    "TestResult",
    "TrainingExample",
    "VerifierManifest",
    "VerifierVersion",
    "Witness",
    "WorkerRequest",
    "WorkerResponse",
    "canonical_bytes",
    "canonical_repr",
    "compare_versions",
    "contract_hash",
    "decode_record",
    "encode_record",
    "manifest_hash",
    "panel_digest",
    "register_verifier",
    "requirement_hash",
    "resolve_command",
    "result_digest",
    "validate_attempt",
    "validate_lineage",
    "validate_matrix",
    "validate_membership",
    "validate_task",
    "validate_verifier",
    "validate_wire_version",
]
